apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name }}"
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.serviceAccount.name }}-role"
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applicationsets"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.rbac.roleBindingName }}"
  namespace: "{{ .Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.serviceAccount.name }}"
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: "{{ .Values.serviceAccount.name }}-role"
  apiGroup: rbac.authorization.k8s.io