apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-operator
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - replica: 1
  template:
    metadata:
      name: 'k8s-operator-{{replica}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bylucasqueiroz/kubernetes-operator
        targetRevision: main
        path: k8s
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true