replicaCount: 1

image:
  repository: k8s-operator
  tag: local
  pullPolicy: Never

serviceAccount:
  name: k8s-operator

rbac:
  roleBindingName: k8s-operator-binding

service:
  name: k8s-operator
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30007

namespace: "operator-default"