apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-operator
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - version: "v1"
            service_name: "k8s-operator"
            namespace: "operator-v1"
          - version: "v2"
            service_name: "k8s-operator"
            namespace: "operator-v2"
  template:
    metadata:
      name: '{{ service_name }}-{{ version }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bylucasqueiroz/kubernetes-operator
        targetRevision: main
        path: manifests/helm/k8s-operator
        helm:
          parameters:
            - name: namespace
              value: '{{ namespace }}'
            - name: serviceAccount.namespace
              value: '{{ namespace }}'
            - name: rbac.roleNamespace
              value: '{{ namespace }}'
            - name: rbac.roleBindingName
              value: '{{ service_name }}-{{ version }}-binding'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true